# Generated by Django 3.1.3 on 2020-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.TextField(max_length=500)),
                ('video', models.TextField(max_length=500)),
                ('description', models.TextField(help_text='Enter a brief description of the courses', max_length=1000)),
            ],
        ),
    ]
