# Generated by Django 3.1.3 on 2020-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.TextField(max_length=500)),
                ('video', models.TextField(max_length=500)),
                ('description', models.TextField(help_text='Enter a brief description of the course', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
    ]
